const BASE_URL = "https://filetoolworks.com";

const blogPosts = [
  { slug: "how-to-compress-wav-files", title: "How to Compress WAV Files Without Ruining Audio Quality", date: "2026-03-01", description: "Five proven methods to reduce WAV file size while keeping audio quality intact. Convert to MP3/FLAC, reduce sample rate, or use online tools." },
  { slug: "mp3-vs-wav", title: "MP3 vs WAV: Quality, File Size, and When to Use Each", date: "2026-03-01", description: "MP3 vs WAV compared. Learn the real differences in quality, file size, and compatibility, plus when each format is the better choice." },
  { slug: "how-to-reduce-audio-file-size", title: "How to Reduce Audio File Size: 5 Methods That Work", date: "2026-03-01", description: "Five practical methods to reduce audio file size: convert formats, lower bitrate, trim silence, reduce sample rate, and compress." },
  { slug: "audio-bitrate-explained", title: "Audio Bitrate Explained: What It Means and How to Choose", date: "2026-03-01", description: "Audio bitrate measures how much data is used per second of audio. Learn what bitrate means, how it affects quality, and which setting to pick." },
  { slug: "flac-to-mp3", title: "FLAC to MP3: How to Convert and What You Lose", date: "2026-03-01", description: "How to convert FLAC to MP3, what quality you lose in the process, and which bitrate setting gives the best balance of size and sound." },
  { slug: "mp3-to-wav-conversion", title: "How to Convert MP3 to WAV (Free, No Software Needed)", date: "2026-03-01", description: "Convert MP3 to WAV format for free using browser-based tools. No software installation needed, works on any device." },
  { slug: "best-audio-format-for-web", title: "Best Audio Format for Web: MP3, OGG, AAC, or WAV?", date: "2026-03-01", description: "Compare MP3, OGG, AAC, and WAV for web use. Find the best audio format for websites based on file size, quality, and browser support." },
  { slug: "ogg-vs-mp3", title: "OGG vs MP3: Quality, Compatibility, and Which to Use", date: "2026-03-01", description: "OGG vs MP3 compared on quality, file size, and device support. Learn which audio format fits your needs and how to convert between them." },
  { slug: "how-to-compress-podcast-audio", title: "How to Compress Podcast Audio Without Losing Voice Quality", date: "2026-03-01", description: "Compress podcast audio files to meet platform upload limits while keeping voice clarity. Covers bitrate, format choice, and practical tools." },
  { slug: "how-to-extract-audio-from-video", title: "How to Extract Audio from Video (Free, Any Format)", date: "2026-03-01", description: "Extract audio tracks from video files as MP3, WAV, or AAC. Free browser-based tool works with MP4, MOV, AVI, and more." },
  { slug: "png-vs-jpg", title: "PNG vs JPG: When to Use Each Format", date: "2026-03-01", description: "PNG vs JPG compared on quality, file size, transparency, and use cases. Learn when to use each image format." },
  { slug: "heic-vs-jpg", title: "HEIC vs JPG: Which Image Format Should You Use?", date: "2026-03-01", description: "HEIC vs JPG compared on file size, quality, and compatibility. Learn which image format to use and how to convert between them." },
  { slug: "webp-vs-png", title: "WebP vs PNG: File Size, Quality, and When to Use Each", date: "2026-03-01", description: "WebP vs PNG compared on file size, quality, transparency support, and browser compatibility. Find out which format fits your needs." },
  { slug: "svg-vs-png", title: "SVG vs PNG: When to Use Each Format", date: "2026-03-01", description: "SVG vs PNG compared for web use. Learn the key differences in scalability, file size, and when each image format is the right choice." },
  { slug: "best-image-format-for-web", title: "Best Image Format for Web: JPG, PNG, WebP Compared", date: "2026-03-01", description: "Compare JPG, PNG, and WebP for web use. Choose the best image format based on file size, quality, transparency needs, and browser support." },
  { slug: "dpi-vs-ppi", title: "DPI vs PPI: What Is the Difference?", date: "2026-03-01", description: "DPI and PPI both measure resolution but in different contexts. Learn what each means, when it matters, and how to set the right values." },
  { slug: "how-to-resize-images-without-losing-quality", title: "How to Resize Images Without Losing Quality", date: "2026-03-01", description: "Resize images without losing quality using the right tools and techniques. Covers downscaling, upscaling, and format-aware resizing." },
  { slug: "how-to-compress-images-for-email", title: "How to Compress Images for Email (Under 1MB Fast)", date: "2026-03-01", description: "Compress images under 1MB for email attachments. Quick methods to reduce image file size without visible quality loss." },
  { slug: "how-to-convert-webp-to-jpg", title: "How to Convert WebP to JPG (Free, No Upload Required)", date: "2026-03-01", description: "Convert WebP images to JPG format free in your browser. No upload needed, works instantly on any device." },
  { slug: "how-to-convert-heic-to-jpg", title: "How to Convert HEIC to JPG", date: "2026-03-01", description: "Convert HEIC photos from your iPhone to JPG format. Free browser-based conversion with no uploads to external servers." },
  { slug: "how-to-convert-image-to-pdf", title: "How to Convert Image to PDF", date: "2026-03-01", description: "Convert any image to PDF format. Supports JPG, PNG, WebP, and more with page size and orientation options." },
  { slug: "how-to-merge-pdf-files", title: "How to Merge PDF Files Online for Free", date: "2026-03-01", description: "Merge multiple PDF files into one document for free. No signup, no upload to servers, works directly in your browser." },
  { slug: "how-to-split-pdf-pages", title: "How to Split PDF Pages Online", date: "2026-03-01", description: "Split a PDF into separate pages or smaller documents. Free online tool that works in your browser with no file uploads." },
  { slug: "extract-pages-from-pdf", title: "How to Extract Pages from a PDF", date: "2026-03-01", description: "Extract specific pages from a PDF document. Select individual pages or ranges and download a new PDF with just those pages." },
  { slug: "how-to-compress-pdf", title: "How to Compress a PDF Without Losing Quality", date: "2026-03-01", description: "Reduce PDF file size while maintaining text clarity and image quality. Practical compression methods and recommended settings." },
  { slug: "how-to-sign-pdf-online", title: "How to Sign a PDF Online for Free", date: "2026-03-01", description: "Sign PDF documents online for free. Draw or upload your signature, position it on any page, and download the signed PDF." },
  { slug: "pdf-vs-docx", title: "PDF vs DOCX: Differences and When to Use Each", date: "2026-03-01", description: "PDF vs DOCX compared on editing, formatting, compatibility, and file size. Learn when each document format is the right choice." },
  { slug: "how-to-compress-video-for-email", title: "How to Compress Video for Email (Under 25MB)", date: "2026-03-01", description: "Compress video files to fit email attachment limits. Reduce video size below 25MB while keeping reasonable quality." },
  { slug: "how-to-reduce-video-file-size", title: "How to Reduce Video File Size Without Losing Quality", date: "2026-03-01", description: "Reduce video file size using resolution, codec, and bitrate adjustments. Practical methods that preserve visual quality." },
  { slug: "gif-vs-mp4", title: "GIF vs MP4: Which Format Should You Use?", date: "2026-03-01", description: "GIF vs MP4 compared on file size, quality, browser support, and use cases. Learn which video format fits your needs." },
  { slug: "mp4-vs-webm", title: "MP4 vs WebM: File Size, Quality, and Compatibility Compared", date: "2026-03-02", description: "MP4 uses H.264, WebM uses VP9. Compare file size, quality, browser support, and learn which video format to choose for web and sharing." },
  { slug: "how-to-make-gif-from-video", title: "How to Make a GIF from a Video (Best Settings for Small Files)", date: "2026-03-02", description: "Turn any video clip into a GIF with the right FPS, resolution, and duration. Includes platform file size limits for Discord, Twitter, and Slack." },
  { slug: "how-to-convert-mov-to-mp4", title: "How to Convert MOV to MP4 (3 Free Methods)", date: "2026-03-02", description: "Convert MOV to MP4 free using online tools, iMovie on Mac, or VLC. Keep full quality with the right codec settings." },
  { slug: "mp4-vs-mov", title: "MP4 vs MOV: Which Video Format Should You Use?", date: "2026-03-03", description: "MP4 and MOV compared on file size, codec support, compatibility, editing, and streaming. Learn which video format fits your project." },
  { slug: "webp-vs-jpg", title: "WebP vs JPG: File Size, Quality, and Browser Support", date: "2026-03-03", description: "WebP produces 25-34% smaller files than JPG at the same quality. Compare compression, transparency, animation, and browser support." },
  { slug: "jpg-vs-jpeg", title: "JPG vs JPEG: Is There a Difference?", date: "2026-03-03", description: "JPG and JPEG are the same format. The only difference is the file extension. Here is why both exist and which one to use." },
  { slug: "aac-vs-mp3", title: "AAC vs MP3: Quality, Compatibility, and Which to Choose", date: "2026-03-04", description: "AAC delivers better audio quality than MP3 at the same bitrate. Compare sound quality, file size, device support, and streaming use cases." },
  { slug: "avi-vs-mp4", title: "AVI vs MP4: File Size, Quality, and Compatibility Compared", date: "2026-03-04", description: "MP4 produces smaller files with better compression than AVI. Compare file size, codec support, streaming, and compatibility for both video formats." },
  { slug: "wav-vs-flac", title: "WAV vs FLAC: File Size, Quality, and When to Use Each", date: "2026-03-04", description: "FLAC is 30-50% smaller than WAV with zero quality loss. Compare file size, metadata support, compatibility, and use cases for both lossless formats." },
  { slug: "mkv-vs-mp4", title: "MKV vs MP4: File Size, Quality, and Compatibility Compared", date: "2026-03-05", description: "MKV supports unlimited tracks and subtitles, MP4 works everywhere. Compare file size, codec support, streaming, and learn which video format to pick." },
  { slug: "avif-vs-webp", title: "AVIF vs WebP: Compression, Quality, and Browser Support", date: "2026-03-05", description: "AVIF compresses 20% smaller than WebP but decodes slower. Compare quality, file size, browser support, and learn which next-gen image format to use." },
  { slug: "flv-vs-mp4", title: "FLV vs MP4: Why FLV Is Dead and How to Convert", date: "2026-03-05", description: "FLV was built for Flash Player, which is gone. MP4 replaced it everywhere. Compare the two formats and learn how to convert FLV files to MP4." },
  { slug: "wmv-vs-mp4", title: "WMV vs MP4: Compatibility, Quality, and File Size Compared", date: "2026-03-06", description: "WMV is a Windows-only format with shrinking support. MP4 plays everywhere. Compare codec quality, file size, streaming, and when to convert." },
  { slug: "heif-vs-heic", title: "HEIF vs HEIC: What is the Difference?", date: "2026-03-06", description: "HEIF is the container format, HEIC is the HEVC-encoded variant. Learn how they relate, why Apple uses HEIC, and how to convert both to JPG." },
  { slug: "m4a-vs-mp3", title: "M4A vs MP3: Quality, Compatibility, and File Size Compared", date: "2026-03-06", description: "M4A (AAC) sounds better than MP3 at the same bitrate but has narrower device support. Compare quality, file size, and when to use each format." },
  { slug: "best-video-format-for-social-media", title: "Best Video Format for Social Media in 2026", date: "2026-03-07", description: "MP4 with H.264 is the universal video format for social media. See format requirements for YouTube, Instagram, TikTok, Facebook, and LinkedIn." },
  { slug: "lossless-vs-lossy-compression", title: "Lossless vs Lossy Compression: How They Work and When to Use Each", date: "2026-03-07", description: "Lossy compression discards data to shrink files. Lossless keeps every bit intact. Learn how each works for images, audio, and video with real examples." },
  { slug: "png-vs-gif", title: "PNG vs GIF: Color Depth, Animation, and When to Use Each", date: "2026-03-07", description: "PNG supports millions of colors and alpha transparency. GIF is limited to 256 colors but supports animation. Compare both formats and when to use each." },
  { slug: "tiff-vs-png", title: "TIFF vs PNG: File Size, Quality, and When to Use Each", date: "2026-03-08", description: "TIFF is built for print and editing. PNG is built for the web. Compare file size, compression, color space support, and transparency for both formats." },
  { slug: "gif-vs-webp", title: "GIF vs WebP: File Size, Animation, and Quality Compared", date: "2026-03-08", description: "WebP animated images are 64% smaller than GIF with better color depth. Compare file size, animation, transparency, and browser support for both formats." },
  { slug: "flac-vs-alac", title: "FLAC vs ALAC: Lossless Audio Formats Compared", date: "2026-03-08", description: "FLAC and ALAC both deliver identical lossless audio quality. FLAC works everywhere, ALAC works best on Apple devices. Compare compatibility, file size, and features." },
  { slug: "h264-vs-h265", title: "H.264 vs H.265: Compression, Quality, and When to Use Each", date: "2026-03-09", description: "H.265 cuts file size in half compared to H.264 at the same quality, but needs more processing power. Compare codecs for streaming, storage, and editing." },
  { slug: "webm-vs-mkv", title: "WebM vs MKV: Web Streaming vs Media Storage Compared", date: "2026-03-09", description: "WebM is optimized for web browsers with VP8/VP9 codecs. MKV supports unlimited tracks and codecs for local storage. Compare features, size, and compatibility." },
  { slug: "opus-vs-mp3", title: "Opus vs MP3: Audio Quality, File Size, and Compatibility Compared", date: "2026-03-09", description: "Opus sounds better than MP3 at the same bitrate and is the default codec for Discord, WhatsApp, and web audio. Compare quality, size, and device support." },
  { slug: "raw-vs-jpeg", title: "RAW vs JPEG: Quality, File Size, and When to Shoot Each", date: "2026-03-10", description: "RAW captures all sensor data for maximum editing flexibility. JPEG is processed and compressed in-camera for smaller files. Compare quality, size, and workflow." },
  { slug: "bmp-vs-png", title: "BMP vs PNG: File Size, Quality, and When to Use Each", date: "2026-03-10", description: "BMP stores raw uncompressed pixel data. PNG uses lossless compression for smaller files with identical quality. Compare features, transparency, and use cases." },
  { slug: "ogg-vs-flac", title: "OGG vs FLAC: Lossy vs Lossless Audio Compared", date: "2026-03-10", description: "FLAC preserves original audio quality with lossless compression. OGG Vorbis uses lossy compression for much smaller files. Compare quality, size, and use cases." },
  { slug: "aiff-vs-wav", title: "AIFF vs WAV: Differences, Compatibility, and Which to Choose", date: "2026-03-11", description: "AIFF and WAV both store uncompressed lossless audio at identical quality. WAV has broader device support, AIFF stores richer metadata. Compare features and pick the right one." },
  { slug: "wav-vs-aac", title: "WAV vs AAC: Quality, File Size, and When to Use Each", date: "2026-03-11", description: "WAV is uncompressed lossless audio. AAC is lossy but 90% smaller. Compare sound quality, file size, device support, and learn when each format makes sense." },
  { slug: "wma-vs-mp3", title: "WMA vs MP3: Quality, Compatibility, and File Size Compared", date: "2026-03-11", description: "WMA sounds slightly better than MP3 at low bitrates but only works on Windows. MP3 plays everywhere. Compare quality, file size, DRM, and device support." },
  { slug: "cbr-vs-vbr", title: "CBR vs VBR: Constant vs Variable Bitrate Explained", date: "2026-03-12", description: "CBR uses a fixed bitrate throughout the file. VBR adjusts dynamically for better quality per byte. Learn when to use each for audio and video encoding." },
  { slug: "tiff-vs-jpg", title: "TIFF vs JPG: When to Use Each Image Format", date: "2026-03-12", description: "TIFF preserves full image quality for editing and print. JPG compresses images for smaller files ideal for web and sharing. Compare quality, size, and use cases." },
  { slug: "zip-vs-rar", title: "ZIP vs RAR: File Compression Formats Compared", date: "2026-03-12", description: "ZIP is universally supported and works without extra software. RAR offers better compression and error recovery. Compare features, compatibility, and use cases." },
  { slug: "7z-vs-zip", title: "7z vs ZIP: Compression, Compatibility, and Speed Compared", date: "2026-03-13", description: "7z compresses files 30-70% smaller than ZIP but needs extra software. ZIP works on every OS out of the box. Compare compression, speed, and compatibility." },
  { slug: "doc-vs-docx", title: "DOC vs DOCX: What Changed and Does It Matter?", date: "2026-03-13", description: "DOCX replaced DOC in 2007 with smaller file sizes, better formatting, and XML-based structure. Learn the key differences and when the old format still shows up." },
  { slug: "av1-vs-h265", title: "AV1 vs H.265 (HEVC): Compression, Quality, and Compatibility", date: "2026-03-13", description: "AV1 compresses 20-30% better than H.265 and is royalty-free. H.265 has wider device support and faster encoding. Compare quality, speed, and licensing." },
  { slug: "tar-vs-zip", title: "TAR vs ZIP: Archiving, Compression, and Platform Differences", date: "2026-03-14", description: "TAR bundles files without compression and preserves Unix permissions. ZIP compresses and archives in one step with universal OS support. Compare both formats." },
  { slug: "csv-vs-xlsx", title: "CSV vs XLSX: When to Use Each Spreadsheet Format", date: "2026-03-14", description: "CSV is plain text that any program can read. XLSX supports formulas, formatting, and multiple sheets. Compare features, compatibility, and file size." },
  { slug: "ppt-vs-pptx", title: "PPT vs PPTX: File Size, Features, and Compatibility Compared", date: "2026-03-14", description: "PPTX replaced PPT in 2007 with 75% smaller files and XML-based structure. PPT is binary and lacks modern features. Compare both PowerPoint formats." },
  { slug: "odt-vs-docx", title: "ODT vs DOCX: Which Document Format Should You Use?", date: "2026-03-15", description: "ODT is the open standard for documents. DOCX is Microsoft's format. Compare compatibility, features, and file size to pick the right one." },
  { slug: "pdf-vs-epub", title: "PDF vs EPUB: Which Format for Your Document?", date: "2026-03-15", description: "PDF preserves exact layout. EPUB reflows text for different screen sizes. Learn which format works best for ebooks, reports, and reading on mobile." },
  { slug: "xls-vs-xlsx", title: "XLS vs XLSX: Key Differences Between Excel Formats", date: "2026-03-15", description: "XLSX replaced XLS in 2007 with smaller files, more rows, and better compatibility. Learn the key differences and when the old XLS format still matters." },
  { slug: "eps-vs-svg", title: "EPS vs SVG: Differences, Features, and Which to Use", date: "2026-03-16", description: "EPS is a legacy print format. SVG is the web standard for vector graphics. Compare file structure, compatibility, transparency, and learn when to use each." },
  { slug: "flac-vs-mp3", title: "FLAC vs MP3: Quality, File Size, and Compatibility Compared", date: "2026-03-16", description: "FLAC is lossless with identical quality to the original. MP3 is lossy but 80% smaller. Compare audio quality, file size, device support, and pick the right format." },
  { slug: "rtf-vs-docx", title: "RTF vs DOCX: Compatibility, Features, and When to Use Each", date: "2026-03-16", description: "RTF is a simple cross-platform text format. DOCX supports full formatting, macros, and modern features. Compare compatibility, security, file size, and use cases." },
  { slug: "avif-vs-jpeg", title: "AVIF vs JPEG: File Size, Quality, and Compatibility Compared", date: "2026-03-17", description: "AVIF compresses images 50% smaller than JPEG with better quality. Compare file size, browser support, encoding speed, and when each format makes sense." },
  { slug: "gzip-vs-zip", title: "GZIP vs ZIP: Compression, Use Cases, and Key Differences", date: "2026-03-17", description: "GZIP compresses a single file stream while ZIP bundles and compresses multiple files. Compare compression ratio, speed, and when to use each format." },
  { slug: "mov-vs-avi", title: "MOV vs AVI: Quality, File Size, and Compatibility Compared", date: "2026-03-17", description: "MOV is Apple's video format with modern codec support. AVI is a legacy Microsoft format. Compare file size, quality, streaming, and compatibility." },
  { slug: "vp9-vs-h265", title: "VP9 vs H.265 (HEVC): Quality, Speed, and Licensing Compared", date: "2026-03-18", description: "VP9 is royalty-free with strong browser support. H.265 compresses slightly better with wider hardware decoding. Compare quality, encoding speed, and licensing." },
  { slug: "jpeg-xl-vs-avif", title: "JPEG XL vs AVIF: Compression, Quality, and Browser Support", date: "2026-03-18", description: "JPEG XL beats AVIF at high quality and handles huge images. AVIF has full browser support and wins at low bitrates. Compare both next-gen image formats." },
  { slug: "aac-vs-ogg", title: "AAC vs OGG Vorbis: Quality, Compatibility, and File Size", date: "2026-03-18", description: "AAC sounds better at low bitrates and works on Apple devices. OGG Vorbis is open-source with higher max bitrate. Compare quality, size, and device support." },
  { slug: "apng-vs-gif", title: "APNG vs GIF: Color Depth, Transparency, and Animation Compared", date: "2026-03-19", description: "APNG supports 16 million colors and alpha transparency while GIF is limited to 256 colors. Compare file size, browser support, and animation quality." },
  { slug: "prores-vs-h264", title: "ProRes vs H.264: Quality, File Size, and When to Use Each", date: "2026-03-19", description: "ProRes is an editing codec with huge files and maximum quality. H.264 compresses aggressively for delivery. Compare file size, color depth, and workflows." },
  { slug: "m4a-vs-mp4", title: "M4A vs MP4: Same Container, Different Contents Explained", date: "2026-03-19", description: "M4A and MP4 both use the MPEG-4 container. M4A holds audio only (AAC or ALAC), while MP4 includes video. Compare compatibility, quality, and use cases." },
  { slug: "opus-vs-aac", title: "Opus vs AAC: Quality, Latency, and Compatibility Compared", date: "2026-03-20", description: "Opus beats AAC at low bitrates and handles voice and music in one codec. AAC has broader device support. Compare quality, latency, file size, and use cases." },
  { slug: "mkv-vs-avi", title: "MKV vs AVI: Features, File Size, and Compatibility Compared", date: "2026-03-20", description: "MKV supports modern codecs, multiple audio tracks, and subtitles. AVI is a legacy format with broad playback support. Compare features, quality, and use cases." },
  { slug: "mpeg-vs-mp4", title: "MPEG vs MP4: Format Differences, Codecs, and Compatibility", date: "2026-03-20", description: "MPEG is a family of compression standards (MPEG-1, MPEG-2, MPEG-4). MP4 is a container format based on MPEG-4 Part 14. Compare codecs, quality, and use cases." },
  { slug: "rar-vs-7z", title: "RAR vs 7z: Compression, Speed, and Compatibility Compared", date: "2026-03-21", description: "RAR offers better speed and error recovery. 7z achieves higher compression with AES-256 encryption and is completely free. Compare compression ratio, speed, and features." },
  { slug: "alac-vs-aac", title: "ALAC vs AAC: Apple Lossless vs Lossy Audio Compared", date: "2026-03-21", description: "ALAC preserves full audio quality in Apple's lossless format. AAC delivers good quality at 90% smaller file sizes. Compare quality, file size, and compatibility." },
  { slug: "heic-vs-png", title: "HEIC vs PNG: File Size, Quality, and Compatibility Compared", date: "2026-03-21", description: "HEIC files are 60-70% smaller than PNG at similar quality. PNG offers lossless quality and universal compatibility. Compare file size, transparency, and use cases." },
  { slug: "av1-vs-vp9", title: "AV1 vs VP9: Compression, Quality, and Performance Compared", date: "2026-03-22", description: "AV1 compresses 30-50% better than VP9 but encodes much slower. VP9 has broader device support and faster real-time performance. Full codec comparison." },
  { slug: "wav-vs-ogg", title: "WAV vs OGG: Quality, File Size, and Compatibility Compared", date: "2026-03-22", description: "WAV is uncompressed with perfect audio quality but 10x larger files. OGG offers great quality at a fraction of the size. Compare formats, use cases, and compatibility." },
  { slug: "json-vs-csv", title: "JSON vs CSV: Structure, Performance, and Use Cases Compared", date: "2026-03-22", description: "CSV is smaller and faster for flat tabular data. JSON handles nested structures and mixed data types. Compare file size, parsing speed, and when to use each format." },
  { slug: "xml-vs-json", title: "XML vs JSON: Syntax, Performance, and When to Use Each", date: "2026-03-23", description: "JSON is lighter and faster for APIs and web apps. XML is better for complex documents and strict validation. Compare syntax, file size, parsing speed, and use cases." },
  { slug: "yaml-vs-json", title: "YAML vs JSON: Readability, Features, and Best Use Cases", date: "2026-03-23", description: "YAML is more readable and supports comments, making it ideal for config files. JSON is faster to parse and better for APIs. See when to use each format." },
  { slug: "png-vs-pdf", title: "PNG vs PDF: Image Format vs Document Format Compared", date: "2026-03-23", description: "PNG is a raster image format for web graphics and screenshots. PDF is a document format for multi-page content and printing. Compare quality, size, and use cases." },
  { slug: "webp-vs-heic", title: "WebP vs HEIC: Format Differences, Compression, and Compatibility", date: "2026-03-24", description: "WebP works everywhere on the web with 96% browser support. HEIC compresses 50% better than JPEG but is limited to Apple devices. Full format comparison." },
  { slug: "h264-vs-vp9", title: "H.264 vs VP9: Codec Comparison for Streaming and Video", date: "2026-03-24", description: "VP9 compresses 30-50% better than H.264 but encodes slower. H.264 has universal device support and faster real-time performance. Full codec comparison." },
  { slug: "aac-vs-flac", title: "AAC vs FLAC: Lossy Convenience vs Lossless Quality", date: "2026-03-24", description: "AAC files are 10x smaller than FLAC and sound nearly identical to most listeners. FLAC preserves every bit of the original audio. Full format comparison." },
  { slug: "mp3-vs-mp4", title: "MP3 vs MP4: Key Differences Between Audio and Multimedia Formats", date: "2026-03-25", description: "MP3 is an audio-only format. MP4 is a multimedia container for video, audio, and subtitles. Compare file size, quality, compatibility, and use cases." },
  { slug: "aiff-vs-mp3", title: "AIFF vs MP3: Quality, File Size, and When to Use Each", date: "2026-03-25", description: "AIFF is uncompressed with full audio quality. MP3 is 10x smaller with lossy compression. Compare sound quality, file size, and compatibility." },
  { slug: "wma-vs-aac", title: "WMA vs AAC: Audio Quality, File Size, and Compatibility Compared", date: "2026-03-25", description: "AAC sounds better than WMA at the same bitrate and works on more devices. WMA is a legacy Windows format with shrinking support. Full comparison." },
  { slug: "midi-vs-mp3", title: "MIDI vs MP3: Instructions vs Recorded Audio Explained", date: "2026-03-26", description: "MIDI stores musical instructions, not actual sound. MP3 stores compressed recorded audio. Compare file size, quality, compatibility, and when to use each format." },
  { slug: "mp4-vs-ts", title: "MP4 vs TS: Container Formats for Streaming and Storage", date: "2026-03-26", description: "MP4 is the standard container for video downloads and playback. TS (MPEG Transport Stream) is built for broadcasting and live streaming. Compare features and use cases." },
  { slug: "pdf-vs-html", title: "PDF vs HTML: Fixed Layout vs Flexible Web Content", date: "2026-03-26", description: "PDF preserves exact layout for print and legal documents. HTML adapts to any screen size for web content. Compare formatting, accessibility, and when to use each." },
  { slug: "epub-vs-mobi", title: "EPUB vs MOBI: eBook Formats Compared", date: "2026-03-27", description: "EPUB is the universal eBook standard supported by almost every reader. MOBI is Amazon's legacy format, now largely replaced. Compare features, compatibility, and which to use." },
  { slug: "psd-vs-png", title: "PSD vs PNG: Editing Format vs Distribution Format", date: "2026-03-27", description: "PSD is Adobe Photoshop's layered editing format. PNG is a compressed image for sharing and the web. Compare features, file size, transparency, and when to use each." },
  { slug: "avi-vs-wmv", title: "AVI vs WMV: Microsoft's Video Formats Compared", date: "2026-03-27", description: "AVI stores high-quality uncompressed video in large files. WMV compresses aggressively for streaming and sharing. Compare file size, quality, compatibility, and modern alternatives." },
  { slug: "ttf-vs-otf", title: "TTF vs OTF: Font Format Differences and Which to Use", date: "2026-03-28", description: "TTF uses quadratic curves and is universally compatible. OTF supports advanced typography features in a smaller file. Compare font formats, features, and pick the right one." },
  { slug: "jpg-vs-gif", title: "JPG vs GIF: When to Use Each Image Format", date: "2026-03-28", description: "JPG handles photos with millions of colors and small file sizes. GIF supports animation and transparency but only 256 colors. Compare both formats and pick the right one." },
  { slug: "svg-vs-pdf", title: "SVG vs PDF: Vector Formats for Web and Print Compared", date: "2026-03-28", description: "SVG is the web standard for scalable vector graphics with animation support. PDF preserves exact layout for print and documents. Compare features, use cases, and compatibility." },
  { slug: "bmp-vs-jpg", title: "BMP vs JPG: File Size, Quality, and When to Use Each", date: "2026-03-29", description: "BMP stores uncompressed pixel data for perfect quality but huge files. JPG uses lossy compression for much smaller files. Compare both image formats and pick the right one." },
  { slug: "tiff-vs-pdf", title: "TIFF vs PDF: Quality, File Size, and Best Use Cases", date: "2026-03-29", description: "TIFF preserves lossless image quality for printing and scanning. PDF is smaller, searchable, and better for sharing documents. Compare both formats for your needs." },
  { slug: "3gp-vs-mp4", title: "3GP vs MP4: Quality, Compatibility, and Which to Use", date: "2026-03-29", description: "3GP was designed for old mobile phones with limited bandwidth. MP4 supports HD/4K and plays everywhere. Compare both video formats and learn when to convert." },
  { slug: "avif-vs-png", title: "AVIF vs PNG: Compression, Quality, and When to Use Each", date: "2026-03-30", description: "AVIF compresses photos 10x smaller than PNG with minimal quality loss. PNG is lossless with universal support. Compare file size, features, and pick the right format." },
  { slug: "woff-vs-ttf", title: "WOFF vs TTF: Font Formats for Web and Desktop Compared", date: "2026-03-30", description: "WOFF is 40-50% smaller than TTF and built for web delivery. TTF is the standard desktop font format. Compare file size, browser support, and when to use each." },
  { slug: "markdown-vs-html", title: "Markdown vs HTML: Syntax, Features, and When to Use Each", date: "2026-03-30", description: "Markdown is simple and readable for writing content. HTML gives full control over layout and interactivity. Compare syntax, use cases, and pick the right format." },
  { slug: "woff2-vs-woff", title: "WOFF2 vs WOFF: Compression, Browser Support, and Which to Use", date: "2026-03-31", description: "WOFF2 is 30% smaller than WOFF thanks to Brotli compression and has 97%+ browser support. Compare file size, performance, and when to use each web font format." },
  { slug: "m4v-vs-mp4", title: "M4V vs MP4: DRM, Compatibility, and Key Differences", date: "2026-03-31", description: "M4V is Apple's DRM-protected video format based on MP4. MP4 plays everywhere. Compare compatibility, codecs, file size, and when to use each format." },
  { slug: "bzip2-vs-gzip", title: "Bzip2 vs Gzip: Compression Ratio, Speed, and When to Use Each", date: "2026-03-31", description: "Bzip2 compresses 10-20% better than gzip but decompresses 6x slower. Compare compression speed, ratio, and use cases for Linux and server environments." },
  { slug: "raw-vs-dng", title: "RAW vs DNG: File Size, Compatibility, and Which to Shoot", date: "2026-04-01", description: "DNG is Adobe's open raw format that is 15-20% smaller than proprietary RAW files. Compare editing flexibility, compatibility, metadata handling, and archival use." },
  { slug: "gif-vs-svg", title: "GIF vs SVG: Animation, File Size, and When to Use Each", date: "2026-04-01", description: "GIF is a raster format limited to 256 colors. SVG is vector-based, scalable, and interactive. Compare animation, file size, browser support, and best use cases." },
  { slug: "mov-vs-mkv", title: "MOV vs MKV: Compatibility, Features, and Which to Choose", date: "2026-04-01", description: "MOV is Apple's video format for editing. MKV is an open container with unlimited tracks and chapters. Compare compatibility, features, file size, and use cases." },
  { slug: "tiff-vs-bmp", title: "TIFF vs BMP: Compression, Quality, and When to Use Each", date: "2026-04-02", description: "TIFF supports lossless compression and layers while BMP stores raw uncompressed pixels. Compare file size, quality, features, and best use cases for each format." },
  { slug: "cr2-vs-jpg", title: "CR2 vs JPG: Canon RAW vs JPEG for Photos", date: "2026-04-02", description: "CR2 is Canon's RAW format with full sensor data and editing flexibility. JPG is compressed and ready to share. Compare quality, file size, and when to shoot each." },
  { slug: "ico-vs-png", title: "ICO vs PNG: Which Format for Favicons and Icons?", date: "2026-04-02", description: "ICO bundles multiple icon sizes in one file while PNG offers better compression and transparency. Compare browser support, file size, and when to use each for favicons." },
  { slug: "pdf-vs-jpg", title: "PDF vs JPG: Key Differences and When to Use Each", date: "2026-04-03", description: "PDF preserves document layout with text and multi-page support. JPG is a compressed image format ideal for photos. Compare quality, file size, editing, and best use cases." },
  { slug: "svg-vs-ai", title: "SVG vs AI: Open Standard vs Adobe's Proprietary Vector Format", date: "2026-04-03", description: "SVG is an open XML-based vector format for the web. AI is Adobe Illustrator's proprietary format for print design. Compare compatibility, features, and use cases." },
  { slug: "keynote-vs-pptx", title: "Keynote vs PPTX: Apple vs Microsoft Presentation Formats Compared", date: "2026-04-03", description: "Keynote (.key) is free on Apple devices with polished animations. PPTX is the industry standard that works everywhere. Compare compatibility, features, and export options." },
  { slug: "ods-vs-xlsx", title: "ODS vs XLSX: Open Document vs Excel Spreadsheet Format", date: "2026-04-04", description: "ODS is the open standard spreadsheet format for LibreOffice and OpenOffice. XLSX is Microsoft Excel's format. Compare compatibility, features, and when to use each." },
  { slug: "xml-vs-csv", title: "XML vs CSV: Structure, File Size, and When to Use Each", date: "2026-04-04", description: "CSV is plain text with comma-separated values for flat tabular data. XML uses tags for hierarchical structured data. Compare file size, parsing, and best use cases." },
  { slug: "dng-vs-jpg", title: "DNG vs JPG: RAW Quality vs Compressed Photos", date: "2026-04-04", description: "DNG is Adobe's open raw format with full editing flexibility. JPG is compressed and ready to share. Compare quality, file size, editing options, and when to use each." },
  { slug: "pages-vs-docx", title: "Pages vs DOCX: Apple Pages vs Microsoft Word Format Compared", date: "2026-04-05", description: "Pages (.pages) is free on Apple devices with clean templates. DOCX is the universal standard for documents. Compare compatibility, features, and when to use each format." },
  { slug: "numbers-vs-excel", title: "Numbers vs Excel: Apple Numbers vs Microsoft Excel Compared", date: "2026-04-05", description: "Apple Numbers is free with beautiful templates. Excel has 420+ functions and is the industry standard. Compare features, formulas, compatibility, and pricing." },
  { slug: "xml-vs-yaml", title: "XML vs YAML: Markup Language vs Data Serialization Compared", date: "2026-04-05", description: "YAML is human-readable and used for config files. XML supports validation and complex document structures. Compare syntax, use cases, parsing, and readability." },
  { slug: "psd-vs-tiff", title: "PSD vs TIFF: Which Format for Editing and Archiving Photos", date: "2026-04-06", description: "PSD is Adobe's native format with full layer support. TIFF is a universal lossless format. Compare compatibility, file size, features, and which to use for your workflow." },
  { slug: "raw-vs-tiff", title: "RAW vs TIFF: Choosing Between Capture and Output Formats", date: "2026-04-06", description: "RAW stores unprocessed sensor data for maximum editing flexibility. TIFF is a lossless processed format for archival and delivery. Compare quality, workflow, and best uses." },
  { slug: "pdf-vs-pptx", title: "PDF vs PPTX: When to Use Each for Presentations and Documents", date: "2026-04-06", description: "PDF preserves formatting across all devices. PPTX supports animations, editing, and live presenting. Compare features, compatibility, file size, and best use cases." },
  { slug: "h264-vs-av1", title: "H.264 vs AV1: Codec Comparison for Streaming and Video", date: "2026-04-07", description: "H.264 offers universal compatibility and fast encoding. AV1 delivers 50% better compression and is royalty-free. Compare quality, speed, support, and which codec to choose." },
  { slug: "csv-vs-tsv", title: "CSV vs TSV: Difference Between Comma and Tab Delimited Files", date: "2026-04-07", description: "CSV uses commas as delimiters. TSV uses tabs. Compare parsing complexity, compatibility, performance, and which format to pick for your data." },
  { slug: "html-vs-xml", title: "HTML vs XML: Key Differences Between Markup Languages", date: "2026-04-07", description: "HTML displays content in web browsers. XML stores and transports structured data. Compare syntax, purpose, flexibility, and when to use each markup language." },
  { slug: "flac-vs-opus", title: "FLAC vs Opus: Lossless vs Lossy Audio Quality Compared", date: "2026-04-08", description: "FLAC preserves perfect audio quality with lossless compression. Opus delivers near-transparent quality at much smaller file sizes. Compare formats, use cases, and compatibility." },
  { slug: "latex-vs-word", title: "LaTeX vs Word: Which Is Better for Documents?", date: "2026-04-08", description: "LaTeX handles math, citations, and large documents with precision. Word is faster to learn and better for collaboration. Compare features, use cases, and when each makes sense." },
  { slug: "svg-vs-webp", title: "SVG vs WebP: Vector vs Raster for Web Images", date: "2026-04-08", description: "SVG is a vector format that scales infinitely for logos and icons. WebP is a raster format with excellent compression for photos. Compare features, performance, and when to use each." },
  { slug: "stereo-vs-mono", title: "Stereo vs Mono: Differences in Sound, File Size, and Use Cases", date: "2026-04-09", description: "Stereo uses two audio channels for spatial sound. Mono uses one channel for consistent playback. Compare quality, file size, and when each makes sense." },
  { slug: "4k-vs-1080p", title: "4K vs 1080p: Resolution, File Size, and Quality Differences", date: "2026-04-09", description: "4K has four times the pixels of 1080p for sharper video, but files are 4x larger. Compare resolution, file size, hardware needs, and when each makes sense." },
  { slug: "vector-vs-raster", title: "Vector vs Raster: Key Differences Between Image Types", date: "2026-04-09", description: "Vector images use math to scale infinitely without quality loss. Raster images use pixels and lose clarity when enlarged. Compare formats, use cases, and file sizes." },
  { slug: "rgb-vs-cmyk", title: "RGB vs CMYK: What's the Difference and When to Use Each", date: "2026-04-10", description: "RGB uses light for screens, CMYK uses ink for print. Understand the key differences in color range, file formats, and when to pick each color mode." },
  { slug: "30fps-vs-60fps", title: "30fps vs 60fps: Which Frame Rate Should You Choose?", date: "2026-04-10", description: "30fps is standard for most video content. 60fps is smoother for action and gaming. Compare file sizes, use cases, and when each frame rate makes sense." },
  { slug: "1080i-vs-1080p", title: "1080i vs 1080p: What's the Difference?", date: "2026-04-10", description: "1080i uses interlaced scanning while 1080p uses progressive scan. Both are 1920x1080 but display images differently. Learn which is better for your use case." },
];

function escapeXml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

export async function GET() {
  const items = blogPosts
    .map(
      (post) => `    <item>
      <title>${escapeXml(post.title)}</title>
      <link>${BASE_URL}/blog/${post.slug}</link>
      <guid isPermaLink="true">${BASE_URL}/blog/${post.slug}</guid>
      <description>${escapeXml(post.description)}</description>
      <pubDate>${new Date(post.date + "T12:00:00Z").toUTCString()}</pubDate>
    </item>`
    )
    .join("\n");

  const feed = `<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>FileToolWorks Blog</title>
    <link>${BASE_URL}/blog</link>
    <description>Practical guides on file formats, conversion, and compression.</description>
    <language>en-us</language>
    <lastBuildDate>${new Date().toUTCString()}</lastBuildDate>
    <atom:link href="${BASE_URL}/feed.xml" rel="self" type="application/rss+xml"/>
${items}
  </channel>
</rss>`;

  return new Response(feed, {
    headers: {
      "Content-Type": "application/xml; charset=utf-8",
      "Cache-Control": "public, max-age=3600, s-maxage=3600",
    },
  });
}
