import { MetadataRoute } from 'next'

const BASE_URL = 'https://filetoolworks.com'

// All tools - matches actual pages in /app folder
const tools = [
  // Image Tools (15)
  'image-to-pdf',
  'heic-to-jpg',
  'png-to-jpg',
  'jpg-to-png',
  'webp-to-jpg',
  'webp-to-png',
  'compress-image',
  'resize-image',
  'rotate-image',
  'image-to-webp',
  'crop-image',
  'sharpen-image',
  'blur-image',
  'remove-background',
  'image-to-heic',

  // PDF Tools (10)
  'compress-pdf',
  'merge-pdf',
  'split-pdf',
  'pdf-to-jpg',
  'jpg-to-pdf',
  'pdf-to-text',
  'extract-pdf-pages',
  'html-to-pdf',
  'sign-pdf',
  'pdf-to-word',

  // Video Tools (5)
  'compress-video',
  'video-to-gif',
  'trim-video',
  'video-to-mp4',
  'video-to-webm',

  // Audio Tools (5)
  'extract-audio',
  'compress-audio',
  'trim-audio',
  'wav-to-mp3',
  'mp3-to-wav',

  // Document Tools (3)
  'word-to-pdf',
  'excel-to-pdf',
  'ppt-to-pdf',

  // Compression Tools (2)
  'zip-files',
  'unzip-files',
]

// Blog posts - matches actual pages in /app/blog folder
const blogPosts = [
  'dpi-vs-ppi',
  'how-to-compress-pdf',
  'how-to-convert-image-to-pdf',
  'how-to-compress-wav-files',
  'mp3-vs-wav',
  'how-to-reduce-audio-file-size',
  'audio-bitrate-explained',
  'png-vs-jpg',
  'how-to-convert-webp-to-jpg',
  'how-to-compress-images-for-email',
  'gif-vs-mp4',
  'how-to-compress-video-for-email',
  'how-to-merge-pdf-files',
  'how-to-split-pdf-pages',
  'extract-pages-from-pdf',
  'how-to-resize-images-without-losing-quality',
  'heic-vs-jpg',
  'how-to-sign-pdf-online',
  'flac-to-mp3',
  'best-image-format-for-web',
  'pdf-vs-docx',
  'mp3-to-wav-conversion',
  'best-audio-format-for-web',
  'ogg-vs-mp3',
  'how-to-compress-podcast-audio',
  'how-to-extract-audio-from-video',
  'webp-vs-png',
  'how-to-convert-heic-to-jpg',
  'how-to-reduce-video-file-size',
  'svg-vs-png',
  'mp4-vs-webm',
  'how-to-make-gif-from-video',
  'how-to-convert-mov-to-mp4',
  'mp4-vs-mov',
  'webp-vs-jpg',
  'jpg-vs-jpeg',
  'aac-vs-mp3',
  'avi-vs-mp4',
  'wav-vs-flac',
  'mkv-vs-mp4',
  'avif-vs-webp',
  'flv-vs-mp4',
  'wmv-vs-mp4',
  'heif-vs-heic',
  'm4a-vs-mp3',
  'best-video-format-for-social-media',
  'lossless-vs-lossy-compression',
  'png-vs-gif',
  'tiff-vs-png',
  'gif-vs-webp',
  'flac-vs-alac',
  'h264-vs-h265',
  'webm-vs-mkv',
  'opus-vs-mp3',
  'raw-vs-jpeg',
  'bmp-vs-png',
  'ogg-vs-flac',
  'aiff-vs-wav',
  'wav-vs-aac',
  'wma-vs-mp3',
  'cbr-vs-vbr',
  'tiff-vs-jpg',
  'zip-vs-rar',
  '7z-vs-zip',
  'doc-vs-docx',
  'av1-vs-h265',
  'tar-vs-zip',
  'csv-vs-xlsx',
  'ppt-vs-pptx',
  'odt-vs-docx',
  'pdf-vs-epub',
  'xls-vs-xlsx',
  'eps-vs-svg',
  'flac-vs-mp3',
  'rtf-vs-docx',
  'avif-vs-jpeg',
  'gzip-vs-zip',
  'mov-vs-avi',
  'vp9-vs-h265',
  'jpeg-xl-vs-avif',
  'aac-vs-ogg',
  'apng-vs-gif',
  'prores-vs-h264',
  'm4a-vs-mp4',
  'opus-vs-aac',
  'mkv-vs-avi',
  'mpeg-vs-mp4',
  'rar-vs-7z',
  'alac-vs-aac',
  'heic-vs-png',
  'av1-vs-vp9',
  'wav-vs-ogg',
  'json-vs-csv',
  'xml-vs-json',
  'yaml-vs-json',
  'png-vs-pdf',
  'webp-vs-heic',
  'h264-vs-vp9',
  'aac-vs-flac',
  'mp3-vs-mp4',
  'aiff-vs-mp3',
  'wma-vs-aac',
  'midi-vs-mp3',
  'mp4-vs-ts',
  'pdf-vs-html',
  'epub-vs-mobi',
  'psd-vs-png',
  'avi-vs-wmv',
  'ttf-vs-otf',
  'jpg-vs-gif',
  'svg-vs-pdf',
  'bmp-vs-jpg',
  'tiff-vs-pdf',
  '3gp-vs-mp4',
  'avif-vs-png',
  'woff-vs-ttf',
  'markdown-vs-html',
  'woff2-vs-woff',
  'm4v-vs-mp4',
  'bzip2-vs-gzip',
  'raw-vs-dng',
  'gif-vs-svg',
  'mov-vs-mkv',
  'tiff-vs-bmp',
  'cr2-vs-jpg',
  'ico-vs-png',
  'pdf-vs-jpg',
  'svg-vs-ai',
  'keynote-vs-pptx',
  'ods-vs-xlsx',
  'xml-vs-csv',
  'dng-vs-jpg',
  'pages-vs-docx',
  'numbers-vs-excel',
  'xml-vs-yaml',
  'psd-vs-tiff',
  'raw-vs-tiff',
  'pdf-vs-pptx',
  'h264-vs-av1',
  'csv-vs-tsv',
  'html-vs-xml',
  'flac-vs-opus',
  'latex-vs-word',
  'svg-vs-webp',
  'stereo-vs-mono',
  '4k-vs-1080p',
  'vector-vs-raster',
  'rgb-vs-cmyk',
  '30fps-vs-60fps',
  '1080i-vs-1080p',
  '720p-vs-1080p',
  '1440p-vs-4k',
  '24fps-vs-30fps',
  '60fps-vs-120fps',
  'hdr-vs-sdr',
  'srgb-vs-adobe-rgb',
  'mpeg4-vs-mp4',
  'avi-vs-mov',
  'nef-vs-jpg',
  '4k-vs-8k',
  'ntsc-vs-pal',
  '8-bit-vs-10-bit',
  'interlaced-vs-progressive',
  '44-1khz-vs-48khz',
  'ac3-vs-aac',
  'cfr-vs-vfr',
  '16-bit-vs-24-bit-audio',
  'zstd-vs-gzip',
  'exfat-vs-ntfs',
  'dolby-digital-vs-dts',
  'pcm-vs-bitstream',
  'fat32-vs-exfat',
  'fat32-vs-ntfs',
  'ext4-vs-ntfs',
]

export default function sitemap(): MetadataRoute.Sitemap {
  const currentDate = new Date()

  // Homepage
  const routes: MetadataRoute.Sitemap = [
    {
      url: BASE_URL,
      lastModified: currentDate,
      changeFrequency: 'daily',
      priority: 1.0,
    },
  ]

  // Tool pages (high priority)
  tools.forEach((tool) => {
    routes.push({
      url: `${BASE_URL}/${tool}`,
      lastModified: currentDate,
      changeFrequency: 'weekly',
      priority: 0.9,
    })
  })

  // Blog index page
  routes.push({
    url: `${BASE_URL}/blog`,
    lastModified: currentDate,
    changeFrequency: 'weekly',
    priority: 0.8,
  })

  // Blog posts
  blogPosts.forEach((post) => {
    routes.push({
      url: `${BASE_URL}/blog/${post}`,
      lastModified: currentDate,
      changeFrequency: 'monthly',
      priority: 0.7,
    })
  })

  return routes
}
